version: '3'

services:
  db:
    container_name: thread-test
    image: mysql:8.0.34
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_DATABASE=test
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
      - MYSQL_ROOT_PASSWORD=admin
      - TZ=Asia/Seoul
    ports:
      - "13306:3306"
    volumes:
      - ./db/init-data.sql:/docker-entrypoint-initdb.d/init-data.sql
